const DAILY_QUEST_POOL = [
  { key: "works", title: "Concluir trabalhos", targetMin: 2, targetMax: 5, rewardXp: 120, rewardCoins: 220 },
  { key: "stealSuccessCount", title: "Roubos bem sucedidos", targetMin: 1, targetMax: 3, rewardXp: 110, rewardCoins: 200 },
  { key: "stealAttempts", title: "Tentar roubos", targetMin: 2, targetMax: 3, rewardXp: 115, rewardCoins: 170 },
  { key: "coinsLifetimeEarned", title: "Ganhar moedas totais", targetMin: 500, targetMax: 2000, rewardXp: 130, rewardCoins: 240 },
  { key: "dailyClaimCount", title: "Resgatar o daily", targetMin: 1, targetMax: 1, rewardXp: 90, rewardCoins: 130 },
  { key: "casinoPlays", title: "Jogar no cassino", targetMin: 2, targetMax: 4, rewardXp: 100, rewardCoins: 180 },
  { key: "gameCoinWin", title: "Vencer Cara ou Coroa", targetMin: 1, targetMax: 3, rewardXp: 125, rewardCoins: 160 },
  { key: "gameGuessExact", title: "Acertar na Adivinhação", targetMin: 1, targetMax: 2, rewardXp: 135, rewardCoins: 190 },
  { key: "gameDadosWin", title: "Vencer Duelo de Dados", targetMin: 1, targetMax: 2, rewardXp: 120, rewardCoins: 175 },
  { key: "gameBatataWin", title: "Vencer Batata Quente", targetMin: 1, targetMax: 2, rewardXp: 130, rewardCoins: 185 },
  { key: "gameRrWin", title: "Ganhar Roleta Russa", targetMin: 1, targetMax: 2, rewardXp: 160, rewardCoins: 250 },
  { key: "lootboxesOpened", title: "Abrir lootboxes", targetMin: 1, targetMax: 3, rewardXp: 140, rewardCoins: 210 },
  { key: "itemsBought", title: "Comprar itens na loja", targetMin: 2, targetMax: 4, rewardXp: 145, rewardCoins: 225 },
  { key: "shieldsUsed", title: "Usar escudos", targetMin: 1, targetMax: 2, rewardXp: 100, rewardCoins: 155 },
  { key: "moneyGameWon", title: "Ganhar moedas em jogos", targetMin: 300, targetMax: 1500, rewardXp: 145, rewardCoins: 220 },
  { key: "moneyCasinoWon", title: "Ganhar moedas no cassino", targetMin: 200, targetMax: 1200, rewardXp: 140, rewardCoins: 210 },
  { key: "questsCompleted", title: "Resgatar missões", targetMin: 1, targetMax: 2, rewardXp: 130, rewardCoins: 195 },
  { key: "gameComandoWin", title: "Vencer Último a Obedecer", targetMin: 1, targetMax: 2, rewardXp: 135, rewardCoins: 200 },
  { key: "gameMemoriaWin", title: "Vencer jogo da Memória", targetMin: 1, targetMax: 2, rewardXp: 130, rewardCoins: 190 },
  { key: "gameReacaoWin", title: "Vencer teste de Reação", targetMin: 1, targetMax: 2, rewardXp: 130, rewardCoins: 190 },
]

const WEEKLY_QUEST_POOL = [
  { key: "weeklyWorks", title: "50+ trabalhos na semana", targetMin: 50, targetMax: 100, rewardXp: 500, rewardCoins: 1200 },
  { key: "weeklyGameWins", title: "Vencer 15+ jogos", targetMin: 15, targetMax: 30, rewardXp: 600, rewardCoins: 1400 },
  { key: "weeklyCoinWins", title: "Vencer 10+ Cara ou Coroas", targetMin: 10, targetMax: 20, rewardXp: 550, rewardCoins: 1300 },
  { key: "weeklyXpEarned", title: "Ganhar 3000+ XP", targetMin: 3000, targetMax: 7000, rewardXp: 700, rewardCoins: 1600 },
  { key: "weeklyCoinsEarned", title: "Ganhar 5000+ moedas", targetMin: 5000, targetMax: 15000, rewardXp: 650, rewardCoins: 1500 },
  { key: "weeklyStealAttempts", title: "Tentar 20+ roubos", targetMin: 20, targetMax: 40, rewardXp: 520, rewardCoins: 1250 },
  { key: "weeklyLootboxes", title: "Abrir 10+ lootboxes", targetMin: 10, targetMax: 25, rewardXp: 580, rewardCoins: 1350 },
  { key: "weeklyTrades", title: "Completar 8+ trocas", targetMin: 8, targetMax: 15, rewardXp: 620, rewardCoins: 1450 },
  { key: "weeklyShields", title: "Usar 5+ escudos", targetMin: 5, targetMax: 12, rewardXp: 480, rewardCoins: 1100 },
  { key: "questMaster", title: "Resgatar 15+ missões", targetMin: 15, targetMax: 30, rewardXp: 580, rewardCoins: 1380 },
  { key: "levelSpike", title: "Subir 3+ níveis", targetMin: 3, targetMax: 8, rewardXp: 800, rewardCoins: 1950 },
  { key: "xpMilestone", title: "10k+ XP na semana", targetMin: 1, targetMax: 1, rewardXp: 1000, rewardCoins: 2400 },
  { key: "undefeated", title: "Semana invicta (10+ jogos)", targetMin: 10, targetMax: 25, rewardXp: 800, rewardCoins: 1950 },
  { key: "forgemaster", title: "Fabricar 5+ passes", targetMin: 5, targetMax: 10, rewardXp: 700, rewardCoins: 1700 },
  { key: "works", title: "Concluir trabalhos", targetMin: 20, targetMax: 45, rewardXp: 520, rewardCoins: 1250 },
  { key: "stealAttempts", title: "Tentar roubos", targetMin: 15, targetMax: 30, rewardXp: 500, rewardCoins: 1200 },
  { key: "stealSuccessCount", title: "Roubos bem sucedidos", targetMin: 5, targetMax: 15, rewardXp: 560, rewardCoins: 1320 },
  { key: "coinsLifetimeEarned", title: "Ganhar moedas totais", targetMin: 8000, targetMax: 25000, rewardXp: 650, rewardCoins: 1500 },
  { key: "dailyClaimCount", title: "Resgatar daily na semana", targetMin: 4, targetMax: 7, rewardXp: 580, rewardCoins: 1380 },
  { key: "casinoPlays", title: "Jogar no cassino", targetMin: 10, targetMax: 25, rewardXp: 530, rewardCoins: 1260 },
  { key: "gameCoinWin", title: "Vitórias em Cara ou Coroa", targetMin: 5, targetMax: 15, rewardXp: 560, rewardCoins: 1320 },
  { key: "gameDadosWin", title: "Vitórias em Duelo de Dados", targetMin: 4, targetMax: 12, rewardXp: 560, rewardCoins: 1320 },
  { key: "gameBatataWin", title: "Vitórias em Batata Quente", targetMin: 4, targetMax: 12, rewardXp: 560, rewardCoins: 1320 },
  { key: "gameRrWin", title: "Vitórias em Roleta Russa", targetMin: 2, targetMax: 8, rewardXp: 620, rewardCoins: 1450 },
  { key: "lootboxesOpened", title: "Abrir lootboxes", targetMin: 6, targetMax: 18, rewardXp: 540, rewardCoins: 1280 },
  { key: "itemsBought", title: "Comprar itens", targetMin: 10, targetMax: 30, rewardXp: 520, rewardCoins: 1240 },
  { key: "shieldsUsed", title: "Usar escudos", targetMin: 4, targetMax: 12, rewardXp: 500, rewardCoins: 1180 },
  { key: "moneyGameWon", title: "Ganhar moedas em jogos", targetMin: 4000, targetMax: 15000, rewardXp: 700, rewardCoins: 1650 },
  { key: "moneyCasinoWon", title: "Ganhar moedas no cassino", targetMin: 3000, targetMax: 12000, rewardXp: 680, rewardCoins: 1600 },
  { key: "questsCompleted", title: "Resgatar missões", targetMin: 6, targetMax: 15, rewardXp: 600, rewardCoins: 1420 },
  { key: "lobbiesStarted", title: "Iniciar lobbies", targetMin: 5, targetMax: 12, rewardXp: 520, rewardCoins: 1250 },
  { key: "gameComandoWin", title: "Vitórias em Último a Obedecer", targetMin: 3, targetMax: 10, rewardXp: 560, rewardCoins: 1320 },
  { key: "gameMemoriaWin", title: "Vitórias no jogo da Memória", targetMin: 3, targetMax: 10, rewardXp: 560, rewardCoins: 1320 },
  { key: "gameReacaoWin", title: "Vitórias no teste de Reação", targetMin: 3, targetMax: 10, rewardXp: 560, rewardCoins: 1320 },
]

module.exports = {
  DAILY_QUEST_POOL,
  WEEKLY_QUEST_POOL,
}
